CREATE OR REPLACE VIEW "RV_TRANSACTION" ( "M_TRANSACTION_ID", "AD_CLIENT_ID", "AD_ORG_ID", "MOVEMENTTYPE", "MOVEMENTDATE", "MOVEMENTQTY", "M_ATTRIBUTESETINSTANCE_ID", "M_ATTRIBUTESET_ID", "SERNO", "LOT", "M_LOT_ID", "GUARANTEEDATE", "M_PRODUCT_ID", "VALUE", "NAME", "DESCRIPTION", "UPC", "SKU", "C_UOM_ID", "M_PRODUCT_CATEGORY_ID", "CLASSIFICATION", "WEIGHT", "VOLUME", "VERSIONNO", "M_LOCATOR_ID", "M_WAREHOUSE_ID", "X", "Y", "Z", "M_INVENTORYLINE_ID", "M_INVENTORY_ID", "M_MOVEMENTLINE_ID", "M_MOVEMENT_ID", "M_INOUTLINE_ID", "M_INOUT_ID", "M_PRODUCTIONLINE_ID", "M_PRODUCTIONPLAN_ID", "M_PRODUCTION_ID", "C_PROJECTISSUE_ID", "C_PROJECT_ID", "LINE", "M_TRANSACTION_CREATED", "M_TRANSACTION_CREATEDBY", "M_TRANSACTION_ISACTIVE", "PP_COST_COLLECTOR_ID", "M_TRANSACTION_UPDATED", "M_TRANSCTION_UPDATEDBY", "M_LOCATOR_AD_ORG_ID", "M_LOCATOR_ISACTIVE", "ISDEFAULT", "PRIORITYNO", "M_LOCATOR_VALUE", "M_PRODUCT_AD_ORG_ID", "M_PRODUCT_COPYFROM", "M_PRODUCT_CREATED", "M_PRODUCT_CREATEDBY", "C_REVENUERECOGNITION_ID", "C_SUBSCRIPTIONTYPE_ID", "C_TAXCATEGORY_ID", "DESCRIPTIONURL", "M_PRODUCT_DISCONTINUED", "M_PRODUCT_DISCONTINUEDAT", "DOCUMENTNOTE", "GROUP1", "GROUP2", "GUARANTEEDAYS", "GUARANTEEDAYSMIN", "HELP", "IMAGEURL", "M_PRODUCT_ISACTIVE", "ISBOM", "ISDROPSHIP", "ISEXCLUDEAUTODELIVERY", "ISINVOICEPRINTDETAILS", "ISPICKLISTPRINTDETAILS", "ISPURCHASED", "ISSELFSERVICE", "ISSOLD", "ISSTOCKED", "M_PRODUCT_ISSUMMARY", "ISVERIFIED", "ISWEBSTOREFEATURED", "LOWLEVEL", "M_PRODUCT_M_ATTRIBUTESET_ID", "M_PRODUCT_M_ASI_ID", "M_FREIGHTCATEGORY_ID", "M_PRODUCT_M_LOCATOR_ID", "M_PRODUCT_PROCESSING", "PRODUCTTYPE", "R_MAILTEXT_ID", "M_PRODUCT_SALESREP_ID", "S_EXPENSETYPE_ID", "SHELFDEPTH", "SHELFHEIGHT", "SHELFWIDTH", "S_RESOURCE_ID", "UNITSPERPACK", "UNITSPERPALLET", "M_PRODUCT_UPDATED", "M_PRODUCT_UPDATEDBY", "M_INVENTORYLINE_AD_ORG_ID", "M_INVENTORYLINE_C_CHARGE_ID", "M_INVENTORYLINE_CREATED", "M_INVENTORYLINE_CREATEDBY", "M_INVENTORYLINE_DESCRIPTION", "INVENTORYTYPE", "M_INVENTORYLINE_ISACTIVE", "M_INVENTORYLINE_M_ASI_ID", "M_INVENTORYLINE_M_LOCATOR_ID", "M_INVENTORYLINE_M_PRODUCT_ID", "M_INVENTORYLINE_PROCESSED", "QTYBOOK", "QTYCOUNT", "QTYCSV", "QTYINTERNALUSE", "M_INVENTORYLINE_REVLINE_ID", "M_INVENTORYLINE_UPDATED", "M_INVENTORYLINE_UPDATEDBY", "M_MOVEMENTLINE_AD_ORG_ID", "M_MOVEMENTLINE_CONFIRMEDQTY", "M_MOVEMENTLINE_CREATED", "M_MOVEMENTLINE_CREATEDBY", "DD_ORDERLINE_ID", "M_MOVEMENTLINE_DESCRIPTION", "M_MOVEMENTLINE_ISACTIVE", "M_MOVEMENTLINE_M_ASI_ID", "M_ATTRIBUTESETINSTANCETO_ID", "M_MOVEMENTLINE_M_LOCATOR_ID", "M_LOCATORTO_ID", "M_MOVEMENTLINE_MOVEMENTQTY", "M_MOVEMENTLINE_M_PRODUCT_ID", "M_MOVEMENTLINE_PROCESSED", "M_MOVEMENTLINE_REVERSALLN_ID", "M_MOVEMENTLINE_SCRAPPEDQTY", "M_MOVEMENTLINE_TARGETQTY", "M_MOVEMENTLINE_UPDATED", "M_MOVEMENTLINE_UPDATEDBY", "M_INOUTLINE_AD_ORG_ID", "M_INOUTLINE_AD_ORGTRX_ID", "M_INOUTLINE_C_ACTIVITY_ID", "M_INOUTLINE_C_CAMPAIGN_ID", "M_INOUTLINE_C_CHARGE_ID", "M_INOUTLINE_CONFIRMEDQTY", "M_INOUTLINE_C_ORDERLINE_ID", "M_INOUTLINE_C_PROJECT_ID", "C_PROJECTPHASE_ID", "C_PROJECTTASK_ID", "M_INOUTLINE_CREATED", "M_INOUTLINE_CREATEDBY", "M_INOUTLINE_C_UOM_ID", "M_INOUTLINE_DESCRIPTION", "M_INOUTLINE_ISACTIVE", "ISDESCRIPTION", "ISINVOICED", "M_INOUTLINE_LINE", "M_INOUTLINE_M_ASI_ID", "M_INOUTLINE_M_INOUT_ID", "M_INOUTLINE_MOVEMENTQTY", "M_INOUTLINE_M_PRODUCT_ID", "M_INOUTLINE_M_RMALINE_ID", "M_INOUTLINE_PICKEDQTY", "M_INOUTLINE_PROCESSED", "M_INOUTLINE_QTYENTERED", "REF_INOUTLINE_ID", "M_INOUTLINE_REVERSALLINE_ID", "M_INOUTLINE_SCRAPPEDQTY", "M_INOUTLINE_TARGETQTY", "M_INOUTLINE_UPDATED", "M_INOUTLINE_UPDATEDBY", "M_INOUTLINE_USER1_ID", "M_INOUTLINE_USER2_ID", "M_PRODUCTIONLINE_AD_ORG_ID", "M_PRODUCTIONLINE_CREATED", "M_PRODUCTIONLINE_CREATEDBY", "M_PRODUCTIONLINE_DESCRIPTION", "M_PRODUCTIONLINE_ISACTIVE", "M_PRODUCTIONLINE_M_ASI_ID", "M_PRODUCTIONLINE_M_LOCATOR_ID", "M_PRODUCTIONLINE_MOVEMENTQTY", "M_PRODUCTIONLINE_M_PRODUCT_ID", "M_PRODUCTIONL_M_PRODUCTIONL_ID", "M_PRODUCTIONLINE_PROCESSED", "M_PRODUCTIONLINE_UPDATED", "M_PRODUCTIONLINE_UPDATEDBY", "M_PRODUCTIONPLAN_AD_ORG_ID", "M_PRODUCTIONPLAN_CREATED", "M_PRODUCTIONPLAN_CREATEDBY", "M_PRODUCTIONPLAN_DESCRIPTION", "M_PRODUCTIONPLAN_ISACTIVE", "M_PRODUCTIONPLAN_LINE", "M_PRODUCTIONPLAN_M_LOCATOR_ID", "M_PRODUCTIONPLAN_M_PRODUCT_ID", "M_PRODUCTIONPLAN_PROCESSED", "M_PRODUCTIONPLAN_PRODUCTIONQT", "M_PRODUCTIONPLAN_UPDATED", "M_PRODUCTIONPLAN_UPDATEDBY", "C_PRJCTISSUE_AD_ORG_ID", "C_PRJCTISSUE_C_PROJECTISSUE_ID", "C_PRJCTISSUE_CREATED", "C_PRJCTISSUE_CREATEDBY", "C_PRJCTISSUE_DESCRIPTION", "C_PRJCTISSUE_ISACTIVE", "C_PRJCTISSUE_M_ASI_ID", "C_PRJCTISSUE_M_INOUTLINE_ID", "C_PRJCTISSUE_M_LOCATOR_ID", "C_PRJCTISSUE_MOVEMENTDATE", "C_PRJCTISSUE_MOVEMENTQTY", "C_PRJCTISSUE_M_PRODUCT_ID", "C_PRJCTISSUE_POSTED", "C_PRJCTISSUE_PROCESSED", "C_PRJCTISSUE_PROCESSEDON", "C_PRJCTISSUE_PROCESSING", "C_PRJCTISSUE_S_TIMEEXPLINE_ID", "C_PRJCTISSUE_UPDATED", "C_PRJCTISSUE_UPDATEDBY", "AD_ORGTRX_ID", "C_CAMPAIGN_ID","C_ACTIVITY_ID", "USER1_ID","USER2_ID" )
AS
SELECT t.m_transaction_id,
         t.ad_client_id,
         t.ad_org_id,
         t.movementtype,
         t.movementdate,
         t.movementqty,
         t.m_attributesetinstance_id,
         asi.m_attributeset_id,
         asi.serno,
         asi.lot,
         asi.m_lot_id,
         asi.guaranteedate,
         t.m_product_id,
         p.value,
         p.name,
         p.description,
         p.upc,
         p.sku,
         p.c_uom_id,
         p.m_product_category_id,
         p.classification,
         p.weight,
         p.volume,
         p.versionno,
         t.m_locator_id,
         l.m_warehouse_id,
         l.x,
         l.y,
         l.z,
         t.m_inventoryline_id,
         il.m_inventory_id,
         t.m_movementline_id,
         ml.m_movement_id,
         t.m_inoutline_id,
         iol.m_inout_id,
         t.m_productionline_id,
         prdl.m_productionplan_id,
         prdp.m_production_id,
         t.c_projectissue_id,
         COALESCE(iol.C_Project_ID,i.C_Project_ID,m.C_Project_ID,io.C_Project_ID,pjl.C_Project_ID) C_Project_ID,
         COALESCE(il.line, ml.line, iol.line, prdl.line, pjl.line) AS line,
         t.created                                                 AS m_transaction_created,
         t.createdby                                               AS m_transaction_createdby,
         t.isactive                                                AS m_transaction_isactive,
         t.pp_cost_collector_id,
         t.updated                                                 AS m_transaction_updated,
         t.updatedby                                               AS m_transction_updatedby,
         l.ad_org_id                                               AS m_locator_ad_org_id,
         l.isactive                                                AS m_locator_isactive,
         l.isdefault,
         l.priorityno,
         l.value                                                   AS m_locator_value,
         p.ad_org_id                                               AS m_product_ad_org_id,
         p.copyfrom                                                AS m_product_copyfrom,
         p.created                                                 AS m_product_created,
         p.createdby                                               AS m_product_createdby,
         p.c_revenuerecognition_id,
         p.c_subscriptiontype_id,
         p.c_taxcategory_id,
         p.descriptionurl,
         p.discontinued                                            AS m_product_discontinued,
         p.discontinuedat                                          AS m_product_discontinuedat,
         p.documentnote,
         p.group1,
         p.group2,
         p.guaranteedays,
         p.guaranteedaysmin,
         p.help,
         p.imageurl,
         p.isactive                                                AS m_product_isactive,
         p.isbom,
         p.isdropship,
         p.isexcludeautodelivery,
         p.isinvoiceprintdetails,
         p.ispicklistprintdetails,
         p.ispurchased,
         p.isselfservice,
         p.issold,
         p.isstocked,
         p.issummary                                               AS m_product_issummary,
         p.isverified,
         p.iswebstorefeatured,
         p.lowlevel,
         p.m_attributeset_id                                       AS m_product_m_attributeset_id,
         p.m_attributesetinstance_id                               AS m_product_m_asi_id,
         p.m_freightcategory_id,
         p.m_locator_id                                            AS m_product_m_locator_id,
         p.processing                                              AS m_product_processing,
         p.producttype,
         p.r_mailtext_id,
         p.salesrep_id                                             AS m_product_salesrep_id,
         p.s_expensetype_id,
         p.shelfdepth,
         p.shelfheight,
         p.shelfwidth,
         p.s_resource_id,
         p.unitsperpack,
         p.unitsperpallet,
         p.updated                                                 AS m_product_updated,
         p.updatedby                                               AS m_product_updatedby,
         il.ad_org_id                                              AS m_inventoryline_ad_org_id,
         il.c_charge_id                                            AS m_inventoryline_c_charge_id,
         il.created                                                AS m_inventoryline_created,
         il.createdby                                              AS m_inventoryline_createdby,
         il.description                                            AS m_inventoryline_description,
         il.inventorytype,
         il.isactive                                               AS m_inventoryline_isactive,
         il.m_attributesetinstance_id                              AS m_inventoryline_m_asi_id,
         il.m_locator_id                                           AS m_inventoryline_m_locator_id,
         il.m_product_id                                           AS m_inventoryline_m_product_id,
         il.processed                                              AS m_inventoryline_processed,
         il.qtybook,
         il.qtycount,
         il.qtycsv,
         il.qtyinternaluse,
         il.reversalline_id                                        AS m_inventoryline_revline_id,
         il.updated                                                AS m_inventoryline_updated,
         il.updatedby                                              AS m_inventoryline_updatedby,
         ml.ad_org_id                                              AS m_movementline_ad_org_id,
         ml.confirmedqty                                           AS m_movementline_confirmedqty,
         ml.created                                                AS m_movementline_created,
         ml.createdby                                              AS m_movementline_createdby,
         ml.dd_orderline_id,
         ml.description                                            AS m_movementline_description,
         ml.isactive                                               AS m_movementline_isactive,
         ml.m_attributesetinstance_id                              AS m_movementline_m_asi_id,
         ml.m_attributesetinstanceto_id,
         ml.m_locator_id                                           AS m_movementline_m_locator_id,
         ml.m_locatorto_id,
         ml.movementqty                                            AS m_movementline_movementqty,
         ml.m_product_id                                           AS m_movementline_m_product_id,
         ml.processed                                              AS m_movementline_processed,
         ml.reversalline_id                                        AS m_movementline_reversalln_id,
         ml.scrappedqty                                            AS m_movementline_scrappedqty,
         ml.targetqty                                              AS m_movementline_targetqty,
         ml.updated                                                AS m_movementline_updated,
         ml.updatedby                                              AS m_movementline_updatedby,
         iol.ad_org_id                                             AS m_inoutline_ad_org_id,
         iol.ad_orgtrx_id                                          AS m_inoutline_ad_orgtrx_id,
         iol.c_activity_id                                         AS m_inoutline_c_activity_id,
         iol.c_campaign_id                                         AS m_inoutline_c_campaign_id,
         iol.c_charge_id                                           AS m_inoutline_c_charge_id,
         iol.confirmedqty                                          AS m_inoutline_confirmedqty,
         iol.c_orderline_id                                        AS m_inoutline_c_orderline_id,
         iol.c_project_id                                          AS m_inoutline_c_project_id,
         iol.c_projectphase_id,
         iol.c_projecttask_id,
         iol.created                                               AS m_inoutline_created,
         iol.createdby                                             AS m_inoutline_createdby,
         iol.c_uom_id                                              AS m_inoutline_c_uom_id,
         iol.description                                           AS m_inoutline_description,
         iol.isactive                                              AS m_inoutline_isactive,
         iol.isdescription,
         iol.isinvoiced,
         iol.line                                                  AS m_inoutline_line,
         iol.m_attributesetinstance_id                             AS m_inoutline_m_asi_id,
         iol.m_inout_id                                            AS m_inoutline_m_inout_id,
         iol.movementqty                                           AS m_inoutline_movementqty,
         iol.m_product_id                                          AS m_inoutline_m_product_id,
         iol.m_rmaline_id                                          AS m_inoutline_m_rmaline_id,
         iol.pickedqty                                             AS m_inoutline_pickedqty,
         iol.processed                                             AS m_inoutline_processed,
         iol.qtyentered                                            AS m_inoutline_qtyentered,
         iol.ref_inoutline_id,
         iol.reversalline_id                                       AS m_inoutline_reversalline_id,
         iol.scrappedqty                                           AS m_inoutline_scrappedqty,
         iol.targetqty                                             AS m_inoutline_targetqty,
         iol.updated                                               AS m_inoutline_updated,
         iol.updatedby                                             AS m_inoutline_updatedby,
         iol.user1_id                                              AS m_inoutline_user1_id,
         iol.user2_id                                              AS m_inoutline_user2_id,
         prdl.ad_org_id                                            AS m_productionline_ad_org_id,
         prdl.created                                              AS m_productionline_created,
         prdl.createdby                                            AS m_productionline_createdby,
         prdl.description                                          AS m_productionline_description,
         prdl.isactive                                             AS m_productionline_isactive,
         prdl.m_attributesetinstance_id                            AS m_productionline_m_asi_id,
         prdl.m_locator_id                                         AS m_productionline_m_locator_id,
         prdl.movementqty                                          AS m_productionline_movementqty,
         prdl.m_product_id                                         AS m_productionline_m_product_id,
         prdl.m_productionline_id                                  AS m_productionl_m_productionl_id,
         prdl.processed                                            AS m_productionline_processed,
         prdl.updated                                              AS m_productionline_updated,
         prdl.updatedby                                            AS m_productionline_updatedby,
         prdp.ad_org_id                                            AS m_productionplan_ad_org_id,
         prdp.created                                              AS m_productionplan_created,
         prdp.createdby                                            AS m_productionplan_createdby,
         prdp.description                                          AS m_productionplan_description,
         prdp.isactive                                             AS m_productionplan_isactive,
         prdp.line                                                 AS m_productionplan_line,
         prdp.m_locator_id                                         AS m_productionplan_m_locator_id,
         prdp.m_product_id                                         AS m_productionplan_m_product_id,
         prdp.processed                                            AS m_productionplan_processed,
         prdp.productionqty                                        AS m_productionplan_productionqt,
         prdp.updated                                              AS m_productionplan_updated,
         prdp.updatedby                                            AS m_productionplan_updatedby,
         pjl.ad_org_id                                             AS c_prjctissue_ad_org_id,
         pjl.c_projectissue_id                                     AS c_prjctissue_c_projectissue_id,
         pjl.created                                               AS c_prjctissue_created,
         pjl.createdby                                             AS c_prjctissue_createdby,
         pjl.description                                           AS c_prjctissue_description,
         pjl.isactive                                              AS c_prjctissue_isactive,
         pjl.m_attributesetinstance_id                             AS c_prjctissue_m_asi_id,
         pjl.m_inoutline_id                                        AS c_prjctissue_m_inoutline_id,
         pjl.m_locator_id                                          AS c_prjctissue_m_locator_id,
         pjl.movementdate                                          AS c_prjctissue_movementdate,
         pjl.movementqty                                           AS c_prjctissue_movementqty,
         pjl.m_product_id                                          AS c_prjctissue_m_product_id,
         pjl.posted                                                AS c_prjctissue_posted,
         pjl.processed                                             AS c_prjctissue_processed,
         pjl.processedon                                           AS c_prjctissue_processedon,
         pjl.processing                                            AS c_prjctissue_processing,
         pjl.s_timeexpenseline_id                                  AS c_prjctissue_s_timeexpline_id,
         pjl.updated                                               AS c_prjctissue_updated,
         pjl.updatedby                                             AS c_prjctissue_updatedby,
		 -- ISY-210
		COALESCE(iol.AD_OrgTrx_ID,i.AD_OrgTrx_ID,m.AD_OrgTrx_ID,io.AD_OrgTrx_ID) AD_OrgTrx_ID,
		COALESCE(iol.C_Campaign_ID,i.C_Campaign_ID,m.C_Campaign_ID,io.C_Campaign_ID) C_Campaign_ID,
		COALESCE(iol.C_Activity_ID,i.C_Activity_ID,m.C_Activity_ID,io.C_Activity_ID) C_Activity_ID,
		COALESCE(iol.User1_ID,i.User1_ID,m.User1_ID,io.User1_ID) User1_ID,
		COALESCE(iol.User2_ID,i.User2_ID,m.User2_ID,io.User2_ID) User2_ID
  FROM   m_transaction t
         JOIN m_locator l
           ON t.m_locator_id = l.m_locator_id
         JOIN m_product p
           ON t.m_product_id = p.m_product_id
         LEFT JOIN m_attributesetinstance asi
                ON t.m_attributesetinstance_id = asi.m_attributesetinstance_id
         LEFT JOIN m_inventoryline il
                ON t.m_inventoryline_id = il.m_inventoryline_id
         LEFT JOIN m_movementline ml
                ON t.m_movementline_id = ml.m_movementline_id
         LEFT JOIN m_inoutline iol
                ON t.m_inoutline_id = iol.m_inoutline_id
         LEFT JOIN m_productionline prdl
                ON t.m_productionline_id = prdl.m_productionline_id
         LEFT JOIN m_productionplan prdp
                ON prdl.m_productionplan_id = prdp.m_productionplan_id
         LEFT JOIN c_projectissue pjl
                ON t.c_projectissue_id = pjl.c_projectissue_id
		LEFT OUTER JOIN M_Inventory i ON (i.M_Inventory_ID = il.M_Inventory_ID)
		LEFT OUTER JOIN M_Movement m ON (m.M_Movement_ID = ml.M_Movement_ID)
		LEFT OUTER JOIN M_InOut io ON (io.M_InOut_ID = iol.M_InOut_ID)
