CREATE OR REPLACE VIEW "adempiere"."z_rv_production" AS
SELECT pr.m_production_id,
    pr.ad_client_id,
    pr.ad_org_id,
    pr.created,
    pr.createdby,
    pr.isactive,
    pr.updated,
    pr.updatedby,
    pr.name,
    pr.description,
    pr.movementdate,
    pr.iscreated,
    pr.posted,
    pr.processed,
    pr.processing,
    pr.ad_orgtrx_id,
    pr.c_project_id,
    pr.c_campaign_id,
    pr.c_activity_id,
    pr.user1_id,
    pr.user2_id,
    pr.processedon,
    pr.m_production_uu,
    pr.documentno,
    pr.m_product_id,
    pr.m_locator_id,
    pr.productionqty,
    pr.datepromised,
    pr.iscomplete,
    pr.c_orderline_id,
    pr.createfrom,
    pr.c_bpartner_id,
    pr.isuseproductionplan
   FROM m_production pr;